version: "3.8"

services:
  ccpex:
    build:
      context: .
    container_name: ccpex
    restart: always
    networks:
      - custom_network
    ports:
      - "5044:3000"

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.0.0/24
